### ISSUE TITLE
lsdj.gb does not work

### ISSUE THREAD

**Issue by OdroidGuy** [retro-esp32/RetroESP32#77]

**Comment by 32teeth** [comment]
Hi @OdroidGuy and welcome to the project.
Our team is not familiar with **_lsdj.gb_**

Would you be able to provide appropriate information as to 'does not work' as in title

Please see our issue form for intake. Thank you

-----
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.


**Additional context**
Add any other context about the problem here.
-----

**Comment by 32teeth** [comment]
Closing due to no response from @OdroidGuy

**Comment by ucodelukas** [comment]
LSDJ is a native tracker for the Gameboy
i will test it on Monday
