### ISSUE TITLE
Can you change the LCD driver?Ili9342 is no longer available in China。

### ISSUE THREAD

**Issue by jianjinliao** [retro-esp32/RetroESP32#85]
Can you change the LCD driver?Ili9342 is no longer available in China。

**Comment by fizarum** [comment]
You can buy it here, for example:
https://a.aliexpress.com/_B1R9Ul

**Comment by jianjinliao** [comment]
this is 37pin LCD，SPI interface is not supported

**Comment by jianjinliao** [comment]
51pin ili9342 LCD is no longer available in China，I bought an ili9342 37pin LCD and found that I couldn't use it without SPI interface

**Comment by 32teeth** [comment]
We are working on an ILI9342C version, please be patient with us

**Comment by jianjinliao** [comment]
Thank you for your reply ， I'll wait for your new version

**Comment by jianjinliao** [comment]
hi,Can PCB files be shared? I want to change the shape, 3D print

**Comment by fizarum** [comment]
hi,
PCB, BOM, etc.  can be found here: https://github.com/retro-esp32/RetroESP32-Design-Files

**Comment by 32teeth** [comment]
@jianjinliao What are you changing the shape to?

Also
-----

> ### Although we do this for 💕 of 🕹️
> **We Also Like Coffee!**
> *Please Consider Supporting*
> [![Support](https://raw.githubusercontent.com/retro-esp32/RetroESP32/master/Assets/sponsor.jpg)](https://github.com/sponsors/retro-esp32)

-----

**Comment by jianjinliao** [comment]
I didn't find the BRD file, I want to change to rectangle similar, I don't have a GB shell

**Comment by 32teeth** [comment]
> I didn't find the BRD file, I want to change to rectangle similar, I don't have a GB shell

That is correct, the BRD file is currently not available, this is due to changing to the newer 45 PIN ILI9342C

That being said, we have not left you alone. Sounds like you are only looking for the Gameboy Pocket (MGB-001) PCB dimensions.

You can find the library file [here](https://github.com/retro-esp32/RetroESP32-Design-Files/blob/master/lbr/RetroESP32.lbr#L2689)

<img width="493" alt="Screen Shot 2020-10-23 at 3 45 06 PM" src="https://user-images.githubusercontent.com/75797/97047319-c4e26f00-1546-11eb-8921-d7445169f1b3.png">

**Comment by 32teeth** [comment]
Closing Issue as link to library and assets provisioned.
